-- public.categories definition

CREATE TABLE public.categories (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	is_active bool NOT NULL,
	icon varchar(100) NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	slug varchar(50) NULL,
	CONSTRAINT categories_slug_key UNIQUE (slug),
	CONSTRAINT product_category_pkey PRIMARY KEY (id)
);
CREATE INDEX categories_slug_9bedfe6b_like ON public.categories USING btree (slug varchar_pattern_ops);


-- public.conveniences definition

CREATE TABLE public.conveniences (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	is_active bool NOT NULL,
	icon varchar(100) NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	slug varchar(50) NULL,
	CONSTRAINT conveniences_slug_key UNIQUE (slug),
	CONSTRAINT product_convenience_pkey PRIMARY KEY (id)
);
CREATE INDEX conveniences_slug_e961fb0d_like ON public.conveniences USING btree (slug varchar_pattern_ops);


-- public.country definition

CREATE TABLE public.country (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	code varchar(10) NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	CONSTRAINT product_country_pkey PRIMARY KEY (id)
);

-- public.faq definition

CREATE TABLE public.faq (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	answer_en text NULL,
	answer_kz text NULL,
	answer_ru text NULL,
	question_en varchar(500) NULL,
	question_kz varchar(500) NULL,
	question_ru varchar(500) NULL,
	CONSTRAINT faq_faq_pkey PRIMARY KEY (id)
);


-- public.help_centers definition

CREATE TABLE public.help_centers (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	email varchar(255) NOT NULL,
	phone_number varchar(128) NULL,
	"text" text NOT NULL,
	is_approved bool NOT NULL,
	CONSTRAINT faq_helpcenter_pkey PRIMARY KEY (id)
);


-- public.types definition

CREATE TABLE public.types (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	icon varchar(100) NULL,
	is_active bool NOT NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	slug varchar(50) NULL,
	CONSTRAINT product_type_pkey PRIMARY KEY (id),
	CONSTRAINT types_slug_key UNIQUE (slug)
);
CREATE INDEX types_slug_56f1b219_like ON public.types USING btree (slug varchar_pattern_ops);


-- public.users definition

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	date_joined timestamptz NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	email varchar(254) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	middle_name varchar(255) NULL,
	date_of_birth date NULL,
	phone_number varchar(128) NULL,
	avatar varchar(100) NULL,
	iin varchar(12) NULL,
	"role" varchar(100) NOT NULL,
	is_superuser bool NOT NULL,
	is_admin bool NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	CONSTRAINT users_email_key UNIQUE (email),
	CONSTRAINT users_phone_number_key UNIQUE (phone_number),
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);
CREATE INDEX users_phone_number_b4cde146_like ON public.users USING btree (phone_number varchar_pattern_ops);

-- public.city definition

CREATE TABLE public.city (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	postall_code varchar(255) NULL,
	country_id int8 NOT NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	CONSTRAINT product_city_pkey PRIMARY KEY (id),
	CONSTRAINT product_city_country_id_0e518b29_fk_product_country_id FOREIGN KEY (country_id) REFERENCES public.country(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_city_country_id_0e518b29 ON public.city USING btree (country_id);

-- public.products definition

CREATE TABLE public.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	price_per_night int4 NOT NULL,
	price_per_week int4 NULL,
	price_per_month int4 NULL,
	rooms_qty int4 NOT NULL,
	guest_qty int4 NOT NULL,
	bed_qty int4 NOT NULL,
	bedroom_qty int4 NOT NULL,
	toilet_qty int4 NULL,
	bath_qty int4 NULL,
	city_id int8 NULL,
	lng varchar(255) NULL,
	lat varchar(255) NULL,
	is_active bool NOT NULL,
	priority text NOT NULL,
	like_count int4 NOT NULL,
	comments_ru text NULL,
	owner_id int8 NOT NULL,
	type_id int8 NOT NULL,
	guests_with_babies bool NOT NULL,
	guests_with_pets bool NOT NULL,
	best_product bool NOT NULL,
	promotion bool NOT NULL,
	country_id int8 NULL,
	phone_number varchar(128) NULL,
	address_en varchar(255) NULL,
	address_kz varchar(255) NULL,
	address_ru varchar(255) NULL,
	comments_en text NULL,
	comments_kz text NULL,
	description_en text NULL,
	description_kz text NULL,
	description_ru text NULL,
	district_en varchar(255) NULL,
	district_kz varchar(255) NULL,
	district_ru varchar(255) NULL,
	name_en varchar(255) NULL,
	name_kz varchar(255) NULL,
	name_ru varchar(255) NULL,
	slug varchar(50) NULL,
	CONSTRAINT product_product_bath_qty_50f0dbf2_check CHECK ((bath_qty >= 0)),
	CONSTRAINT product_product_bed_qty_825fb172_check CHECK ((bed_qty >= 0)),
	CONSTRAINT product_product_bedroom_qty_3ed7bdca_check CHECK ((bedroom_qty >= 0)),
	CONSTRAINT product_product_guest_qty_1f4cc084_check CHECK ((guest_qty >= 0)),
	CONSTRAINT product_product_like_count_check CHECK ((like_count >= 0)),
	CONSTRAINT product_product_pkey PRIMARY KEY (id),
	CONSTRAINT product_product_price_per_month_0a83b6b1_check CHECK ((price_per_month >= 0)),
	CONSTRAINT product_product_price_per_night_122ba3b0_check CHECK ((price_per_night >= 0)),
	CONSTRAINT product_product_price_per_week_70b60e38_check CHECK ((price_per_week >= 0)),
	CONSTRAINT product_product_rooms_qty_6c2e74da_check CHECK ((rooms_qty >= 0)),
	CONSTRAINT product_product_toilet_qty_243a6b48_check CHECK ((toilet_qty >= 0)),
	CONSTRAINT products_slug_8f20884e_uniq UNIQUE (slug),
	CONSTRAINT product_product_owner_id_af246414_fk_users_id FOREIGN KEY (owner_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_product_type_id_db92a7b7_fk_product_type_id FOREIGN KEY (type_id) REFERENCES public."types"(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT products_city_id_dda43a19_fk_product_city_id FOREIGN KEY (city_id) REFERENCES public.city(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT products_country_id_22235cd0_fk_product_country_id FOREIGN KEY (country_id) REFERENCES public.country(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_product_owner_id_af246414 ON public.products USING btree (owner_id);
CREATE INDEX product_product_type_id_db92a7b7 ON public.products USING btree (type_id);
CREATE INDEX products_city_id_dda43a19 ON public.products USING btree (city_id);
CREATE INDEX products_country_id_22235cd0 ON public.products USING btree (country_id);
CREATE INDEX products_guest_q_cfe819_idx ON public.products USING btree (guest_qty);
CREATE INDEX products_name_en_610a06_idx ON public.products USING btree (name_en);
CREATE INDEX products_name_kz_466a79_idx ON public.products USING btree (name_kz);
CREATE INDEX products_name_ru_c9fcdf_idx ON public.products USING btree (name_ru);
CREATE INDEX products_price_p_82684a_idx ON public.products USING btree (price_per_night);
CREATE INDEX products_rooms_q_c12fad_idx ON public.products USING btree (rooms_qty);
CREATE INDEX products_slug_8f20884e_like ON public.products USING btree (slug varchar_pattern_ops);
CREATE INDEX products_type_id_104a22_idx ON public.products USING btree (type_id);


-- public.products_category definition

CREATE TABLE public.products_category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_id int8 NOT NULL,
	category_id int8 NOT NULL,
	CONSTRAINT product_product_category_pkey PRIMARY KEY (id),
	CONSTRAINT product_product_category_product_id_category_id_5e811dc1_uniq UNIQUE (product_id, category_id),
	CONSTRAINT product_product_cate_category_id_c14e57fb_fk_product_c FOREIGN KEY (category_id) REFERENCES public.categories(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_product_cate_product_id_dd5b89f7_fk_product_p FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_product_category_category_id_c14e57fb ON public.products_category USING btree (category_id);
CREATE INDEX product_product_category_product_id_dd5b89f7 ON public.products_category USING btree (product_id);


-- public.products_convenience definition

CREATE TABLE public.products_convenience (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_id int8 NOT NULL,
	convenience_id int8 NOT NULL,
	CONSTRAINT product_product_convenie_product_id_convenience_i_0bf2ea86_uniq UNIQUE (product_id, convenience_id),
	CONSTRAINT product_product_convenience_pkey PRIMARY KEY (id),
	CONSTRAINT product_product_conv_convenience_id_cd090af4_fk_product_c FOREIGN KEY (convenience_id) REFERENCES public.conveniences(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_product_conv_product_id_3879a316_fk_product_p FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_product_convenience_convenience_id_cd090af4 ON public.products_convenience USING btree (convenience_id);
CREATE INDEX product_product_convenience_product_id_3879a316 ON public.products_convenience USING btree (product_id);


-- public.bookings definition

CREATE TABLE public.bookings (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	start_date date NOT NULL,
	end_date date NOT NULL,
	product_id int8 NOT NULL,
	phone varchar(255) NULL,
	user_name varchar(255) NULL,
	CONSTRAINT product_booking_pkey PRIMARY KEY (id),
	CONSTRAINT product_booking_product_id_07f05eff_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX bookings_end_dat_49719f_idx ON public.bookings USING btree (end_date);
CREATE INDEX bookings_start_d_94c02c_idx ON public.bookings USING btree (start_date);
CREATE INDEX product_booking_product_id_07f05eff ON public.bookings USING btree (product_id);


-- public.comments definition

CREATE TABLE public.comments (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	"content" text NOT NULL,
	date_posted timestamptz NOT NULL,
	is_active bool NOT NULL,
	product_id int8 NOT NULL,
	reply_id int8 NULL,
	user_id int8 NOT NULL,
	rating int4 NOT NULL,
	CONSTRAINT comments_rating_check CHECK ((rating >= 0)),
	CONSTRAINT product_comment_pkey PRIMARY KEY (id),
	CONSTRAINT product_comment_product_id_b32e96a2_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_comment_reply_id_f13ef92b_fk_product_comment_id FOREIGN KEY (reply_id) REFERENCES public."comments"(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_comment_user_id_ac70fe86_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_comment_product_id_b32e96a2 ON public.comments USING btree (product_id);
CREATE INDEX product_comment_reply_id_f13ef92b ON public.comments USING btree (reply_id);
CREATE INDEX product_comment_user_id_ac70fe86 ON public.comments USING btree (user_id);


-- public.images definition

CREATE TABLE public.images (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	original varchar(100) NOT NULL,
	thumbnail varchar(100) NULL,
	width int4 NULL,
	height int4 NULL,
	mimetype varchar(300) NULL,
	"size" int4 NULL,
	product_id int8 NULL,
	is_label bool NOT NULL,
	CONSTRAINT product_image_pkey PRIMARY KEY (id),
	CONSTRAINT product_image_product_id_8b9355c5_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_image_product_id_8b9355c5 ON public.images USING btree (product_id);


-- public.likes definition

CREATE TABLE public.likes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	product_id int8 NOT NULL,
	user_id int8 NOT NULL,
	count int4 NOT NULL,
	CONSTRAINT product_like_count_check CHECK ((count >= 0)),
	CONSTRAINT product_like_pkey PRIMARY KEY (id),
	CONSTRAINT product_like_product_id_7ac6ab0f_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_like_user_id_afa8c60b_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_like_product_id_7ac6ab0f ON public.likes USING btree (product_id);
CREATE INDEX product_like_user_id_afa8c60b ON public.likes USING btree (user_id);


-- public.favorites definition

CREATE TABLE public.favorites (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	like_id int8 NOT NULL,
	product_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT product_favorites_pkey PRIMARY KEY (id),
	CONSTRAINT product_favorites_like_id_988f4880_fk_product_like_id FOREIGN KEY (like_id) REFERENCES public.likes(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_favorites_product_id_22c532be_fk_product_product_id FOREIGN KEY (product_id) REFERENCES public.products(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT product_favorites_user_id_04dd8bf2_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX product_favorites_like_id_988f4880 ON public.favorites USING btree (like_id);
CREATE INDEX product_favorites_product_id_22c532be ON public.favorites USING btree (product_id);
CREATE INDEX product_favorites_user_id_04dd8bf2 ON public.favorites USING btree (user_id);