services:
  superapp_backend:
    container_name: superapp_backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./app:/app
    depends_on:
      - superapp_db
    networks:
      - superapp

  superapp_db:
    image: postgres:latest
    container_name: superapp_db
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - superapp

volumes:
  pg_data:

networks:
  superapp:
    driver: bridge
